build:
	ankith_hello: ankith_hello.o
		gcc ankith_hello.o -o ankith_hello
	ankith_hello.o: ankith_hello.c ankith_hello.h
		gcc -c ankith_hello.c -o ankith_hello.o

run:
	./ankith_hello

clean:
	rm ankith_hello
